"""Seed junior game content — minerals, badges, detective cases."""
MINERALS = [
    # ── COMMON ──────────────────────────────────────────────────────────────
    {
        "mineral_id": "quartz",
        "name": "Quartz",
        "family": "Silicate",
        "rarity": "common",
        "mohs_hardness": 7.0,
        "key_property": "Glassy lustre, 6-sided crystal points",
        "ontario_locality": "Found across Ontario's Shield",
        "flavour_text": "The rock world's most popular mineral!",
        "fun_fact": "Quartz makes up about 12% of Earth's crust.",
        "age_easy_description": "A clear or white crystal that looks like glass.",
        "age_standard_description": "Silicon dioxide crystal with distinctive hexagonal prisms.",
        "detective_clues": [
            "It scratches glass easily",
            "Crystal has 6 sides",
            "Feels smooth, not soapy",
            "Breaks with curved, shell-like surfaces",
        ],
        "dig_site_associations": ["bancroft", "haliburton"],
        "province_associations": ["Grenville", "Superior"],
        "card_emoji": "🔮",
        "card_colour": "#e0f2fe",
    },
    {
        "mineral_id": "calcite",
        "name": "Calcite",
        "family": "Carbonate",
        "rarity": "common",
        "mohs_hardness": 3.0,
        "key_property": "Fizzes with acid, perfect rhombic cleavage",
        "ontario_locality": "Caves and limestone outcrops, southern Ontario",
        "flavour_text": "It fizzes — just like pop!",
        "fun_fact": "Calcite makes up most of limestone and marble.",
        "age_easy_description": "A white or clear mineral that fizzes when you put vinegar on it.",
        "age_standard_description": "Calcium carbonate with perfect three-directional cleavage.",
        "detective_clues": [
            "Fizzes with acid or vinegar",
            "Softer than a copper coin",
            "Splits into rhombus shapes",
            "Often white or colourless",
        ],
        "dig_site_associations": ["bancroft"],
        "province_associations": ["Grenville", "Southern and Superior"],
        "card_emoji": "🫧",
        "card_colour": "#f0fdf4",
    },
    {
        "mineral_id": "feldspar",
        "name": "Feldspar",
        "family": "Silicate",
        "rarity": "common",
        "mohs_hardness": 6.0,
        "key_property": "Two cleavage directions at 90°, white or pink",
        "ontario_locality": "Granite outcrops throughout the Shield",
        "flavour_text": "Half of all rocks contain feldspar!",
        "fun_fact": "Feldspar is the most abundant mineral in Earth's crust.",
        "age_easy_description": "A pink or white blocky mineral found in most rocks.",
        "age_standard_description": "Group of framework silicates; orthoclase is pink, plagioclase is white.",
        "detective_clues": [
            "Blocky shape with flat surfaces",
            "Pink, white, or grey in colour",
            "Two cleavage planes meet at right angles",
            "Found in almost every granite",
        ],
        "dig_site_associations": ["bancroft", "haliburton", "madoc"],
        "province_associations": ["Grenville", "Superior"],
        "card_emoji": "🪨",
        "card_colour": "#fdf4ff",
    },
    {
        "mineral_id": "muscovite",
        "name": "Muscovite Mica",
        "family": "Silicate",
        "rarity": "common",
        "mohs_hardness": 2.5,
        "key_property": "Peels into thin silvery sheets",
        "ontario_locality": "Pegmatites in Bancroft and Haliburton",
        "flavour_text": "So shiny you can see your reflection!",
        "fun_fact": "Muscovite was once used as window glass — called 'Muscovy glass'.",
        "age_easy_description": "A sparkly silver mineral that peels into thin sheets like a book.",
        "age_standard_description": "Potassium aluminum silicate with perfect basal cleavage into flexible sheets.",
        "detective_clues": [
            "Peels into very thin flat sheets",
            "Silvery and very shiny",
            "Sheets are flexible and springy",
            "Very soft — fingernail can scratch it",
        ],
        "dig_site_associations": ["bancroft", "haliburton"],
        "province_associations": ["Grenville"],
        "card_emoji": "✨",
        "card_colour": "#fefce8",
    },
    {
        "mineral_id": "pyrite",
        "name": "Pyrite",
        "family": "Sulfide",
        "rarity": "common",
        "mohs_hardness": 6.5,
        "key_property": "Brassy yellow cubes, greenish-black streak",
        "ontario_locality": "Sudbury area and sulfide deposits throughout",
        "flavour_text": "Fool's Gold! Don't be tricked.",
        "fun_fact": "Pyrite was used to start fires — it makes sparks when struck.",
        "age_easy_description": "A shiny yellow mineral shaped like little golden cubes.",
        "age_standard_description": "Iron disulfide forming cubic or pyritohedral crystals; greenish-black streak.",
        "detective_clues": [
            "Shiny brassy yellow colour",
            "Cubic or striated crystal faces",
            "Leaves a greenish-black powder mark",
            "Much harder than gold",
        ],
        "dig_site_associations": ["sudbury"],
        "province_associations": ["Superior"],
        "card_emoji": "🟡",
        "card_colour": "#fefce8",
    },
    {
        "mineral_id": "hornblende",
        "name": "Hornblende",
        "family": "Silicate (Amphibole)",
        "rarity": "common",
        "mohs_hardness": 5.5,
        "key_property": "Black, two cleavages at 60°/120°",
        "ontario_locality": "Found in igneous and metamorphic rocks across Ontario",
        "flavour_text": "The dark mineral that makes granite speckled.",
        "fun_fact": "Hornblende is an amphibole — it contains calcium, sodium, iron, and magnesium.",
        "age_easy_description": "A dark black or dark green mineral found in most rocks.",
        "age_standard_description": "Complex calcium-sodium-iron-magnesium amphibole; two cleavages at ~60°.",
        "detective_clues": [
            "Dark black or very dark green",
            "Two shiny cleavage faces at an angle",
            "Not magnetic",
            "Found in granite and gneiss",
        ],
        "dig_site_associations": ["bancroft", "sudbury"],
        "province_associations": ["Grenville", "Superior"],
        "card_emoji": "⬛",
        "card_colour": "#1e293b",
    },
    {
        "mineral_id": "biotite",
        "name": "Biotite Mica",
        "family": "Silicate",
        "rarity": "common",
        "mohs_hardness": 2.5,
        "key_property": "Black shiny sheets, flexible",
        "ontario_locality": "Granite and gneiss across the Canadian Shield",
        "flavour_text": "Biotite is muscovite's dark twin!",
        "fun_fact": "Biotite is dark because it contains iron and magnesium.",
        "age_easy_description": "A shiny black mineral that peels into thin dark sheets.",
        "age_standard_description": "Iron-magnesium phyllosilicate with perfect basal cleavage; brown to black.",
        "detective_clues": [
            "Black or very dark brown sheets",
            "Peels apart like muscovite",
            "Sheets are flexible",
            "Very soft — fingernail can scratch it",
        ],
        "dig_site_associations": ["bancroft", "haliburton"],
        "province_associations": ["Grenville", "Superior"],
        "card_emoji": "🖤",
        "card_colour": "#334155",
    },
    {
        "mineral_id": "dolomite",
        "name": "Dolomite",
        "family": "Carbonate",
        "rarity": "common",
        "mohs_hardness": 3.5,
        "key_property": "Rhombic crystals, curved saddle faces, slight fizz",
        "ontario_locality": "Dolostone formations in southern Ontario",
        "flavour_text": "Named after the Dolomite Alps in Italy!",
        "fun_fact": "Dolomite only fizzes with acid when powdered — unlike calcite.",
        "age_easy_description": "A white or grey mineral that looks like calcite but doesn't fizz as much.",
        "age_standard_description": "Calcium magnesium carbonate; saddle-shaped curved crystal faces.",
        "detective_clues": [
            "White or cream coloured",
            "Curved crystal faces",
            "Barely fizzes with acid (powdered fizzes more)",
            "Pearly lustre on cleavage surfaces",
        ],
        "dig_site_associations": [],
        "province_associations": ["Southern and Superior"],
        "card_emoji": "🤍",
        "card_colour": "#f8fafc",
    },
    {
        "mineral_id": "magnetite",
        "name": "Magnetite",
        "family": "Oxide",
        "rarity": "common",
        "mohs_hardness": 5.5,
        "key_property": "Black, strongly magnetic",
        "ontario_locality": "Iron formations in northern Ontario",
        "flavour_text": "It's magnetic! It can move a compass needle.",
        "fun_fact": "Magnetite is a natural magnet — lodestone is a variety that was used as a compass.",
        "age_easy_description": "A black mineral that sticks to a magnet.",
        "age_standard_description": "Iron oxide (Fe₃O₄); octahedral crystals; strongly ferrimagnetic.",
        "detective_clues": [
            "Sticks to a magnet",
            "Jet black colour",
            "Black streak",
            "Heavy for its size",
        ],
        "dig_site_associations": ["sudbury"],
        "province_associations": ["Superior"],
        "card_emoji": "🧲",
        "card_colour": "#0f172a",
    },
    {
        "mineral_id": "hematite",
        "name": "Hematite",
        "family": "Oxide",
        "rarity": "common",
        "mohs_hardness": 6.0,
        "key_property": "Red-brown streak even when shiny silver",
        "ontario_locality": "Iron formations, Temagami area",
        "flavour_text": "It looks silver but writes red — magic!",
        "fun_fact": "Hematite is what makes Mars look red — it's iron rust.",
        "age_easy_description": "A silver or reddish mineral that leaves a red line when you scratch it.",
        "age_standard_description": "Iron oxide; metallic lustre when massive; always has characteristic red-brown streak.",
        "detective_clues": [
            "Red or red-brown streak every time",
            "Can be shiny silver OR dull red",
            "Heavier than it looks",
            "Not magnetic (unlike magnetite)",
        ],
        "dig_site_associations": [],
        "province_associations": ["Superior"],
        "card_emoji": "❤️",
        "card_colour": "#7f1d1d",
    },
    {
        "mineral_id": "chlorite",
        "name": "Chlorite",
        "family": "Silicate",
        "rarity": "common",
        "mohs_hardness": 2.5,
        "key_property": "Green, soapy feel, flexible plates",
        "ontario_locality": "Metamorphic rocks across the Shield",
        "flavour_text": "Named for its green colour — 'chloros' means green in Greek!",
        "fun_fact": "Chlorite makes rocks look green and feel slippery.",
        "age_easy_description": "A green mineral that feels soapy and is found in green rocks.",
        "age_standard_description": "Phyllosilicate group; variable green colour; plates are flexible but not elastic.",
        "detective_clues": [
            "Green colour, many shades",
            "Plates feel soapy or slippery",
            "Unlike mica, plates are not springy",
            "Very soft — fingernail scratches it",
        ],
        "dig_site_associations": [],
        "province_associations": ["Grenville", "Superior"],
        "card_emoji": "🟢",
        "card_colour": "#14532d",
    },
    {
        "mineral_id": "sphalerite",
        "name": "Sphalerite",
        "family": "Sulfide",
        "rarity": "common",
        "mohs_hardness": 3.5,
        "key_property": "Resinous to adamantine lustre, yellow-brown streak",
        "ontario_locality": "Zinc deposits near Timmins and Sudbury region",
        "flavour_text": "The main ore of zinc — it's in every battery!",
        "fun_fact": "Sphalerite can be yellow, red, brown, or even black.",
        "age_easy_description": "A shiny reddish or yellowish mineral — the main source of zinc.",
        "age_standard_description": "Zinc sulfide; excellent dodecahedral cleavage; resinous lustre; yellow streak.",
        "detective_clues": [
            "Resinous or diamond-like lustre",
            "Yellow to brown streak",
            "Strong cleavage in multiple directions",
            "Often yellow, orange, or red-brown",
        ],
        "dig_site_associations": [],
        "province_associations": ["Superior"],
        "card_emoji": "🟠",
        "card_colour": "#92400e",
    },
    {
        "mineral_id": "galena",
        "name": "Galena",
        "family": "Sulfide",
        "rarity": "common",
        "mohs_hardness": 2.5,
        "key_property": "Heavy metallic silver cubes, very dense",
        "ontario_locality": "Lead deposits, Cobalt and Madoc areas",
        "flavour_text": "The heaviest-feeling common mineral!",
        "fun_fact": "Galena was used to make bullets and paint — but we know now it's toxic.",
        "age_easy_description": "A very heavy silver-grey mineral that breaks into perfect cubes.",
        "age_standard_description": "Lead sulfide; metallic lustre; perfect cubic cleavage; very high specific gravity.",
        "detective_clues": [
            "Surprisingly heavy for its size",
            "Shiny silver-grey metallic colour",
            "Breaks into perfect cubes",
            "Grey streak",
        ],
        "dig_site_associations": [],
        "province_associations": ["Grenville"],
        "card_emoji": "🪤",
        "card_colour": "#475569",
    },
    {
        "mineral_id": "chalcopyrite",
        "name": "Chalcopyrite",
        "family": "Sulfide",
        "rarity": "common",
        "mohs_hardness": 3.5,
        "key_property": "Brassy yellow with purple tarnish",
        "ontario_locality": "Sudbury nickel-copper complex",
        "flavour_text": "Peacock ore — it turns rainbow colours!",
        "fun_fact": "Chalcopyrite is the world's most important source of copper.",
        "age_easy_description": "A yellow mineral that turns purple and blue on its surface — like a rainbow!",
        "age_standard_description": "Copper iron sulfide; brass-yellow; iridescent purple/blue surface tarnish.",
        "detective_clues": [
            "Brassy yellow like pyrite but softer",
            "Purple or rainbow tarnish on surface",
            "Greenish-black streak",
            "Harder to scratch than calcite",
        ],
        "dig_site_associations": ["sudbury"],
        "province_associations": ["Superior"],
        "card_emoji": "🌈",
        "card_colour": "#713f12",
    },
    {
        "mineral_id": "epidote",
        "name": "Epidote",
        "family": "Silicate",
        "rarity": "common",
        "mohs_hardness": 6.5,
        "key_property": "Pistachio green, striated crystals",
        "ontario_locality": "Altered mafic rocks near Lake Superior",
        "flavour_text": "The pistachio-ice-cream mineral!",
        "fun_fact": "Epidote forms when basalt and gabbro are altered by hot water.",
        "age_easy_description": "A yellowish-green mineral that grows in long striped crystals.",
        "age_standard_description": "Calcium aluminum iron sorosilicate; characteristic pistachio to yellow-green colour.",
        "detective_clues": [
            "Pistachio or olive green colour",
            "Long crystals with striped sides",
            "Vitreous lustre",
            "Harder than a pocket knife",
        ],
        "dig_site_associations": [],
        "province_associations": ["Superior"],
        "card_emoji": "🫛",
        "card_colour": "#365314",
    },
    # ── UNCOMMON ──────────────────────────────────────────────────────────────
    {
        "mineral_id": "apatite",
        "name": "Apatite",
        "family": "Phosphate",
        "rarity": "uncommon",
        "mohs_hardness": 5.0,
        "key_property": "Hexagonal crystals, blue-green or yellow",
        "ontario_locality": "Bancroft, Wilberforce — world-class specimens",
        "flavour_text": "Your teeth are made of apatite!",
        "fun_fact": "Apatite defines 5 on the Mohs scale — named for 'to deceive' in Greek.",
        "age_easy_description": "A blue, green, or yellow mineral shaped like a six-sided pencil.",
        "age_standard_description": "Calcium phosphate group; hexagonal crystals; Mohs 5 reference mineral.",
        "detective_clues": [
            "Hexagonal (6-sided) crystal shape",
            "Blue, green, yellow, or violet colour",
            "Scratched by a pocket knife, but scratches glass",
            "Bancroft is world-famous for it",
        ],
        "dig_site_associations": ["bancroft", "wilberforce"],
        "province_associations": ["Grenville"],
        "card_emoji": "💙",
        "card_colour": "#1e3a5f",
    },
    {
        "mineral_id": "tourmaline",
        "name": "Tourmaline",
        "family": "Silicate (Cyclosilicate)",
        "rarity": "uncommon",
        "mohs_hardness": 7.5,
        "key_property": "Striated triangular prisms, often black",
        "ontario_locality": "Pegmatites in Bancroft and Haliburton areas",
        "flavour_text": "The mineral with the most colours in the world!",
        "fun_fact": "Some tourmaline crystals are two colours at once — called watermelon tourmaline.",
        "age_easy_description": "A long black crystal with lines running along its length — like a pencil.",
        "age_standard_description": "Complex boron cyclosilicate; striated prisms with triangular cross-section.",
        "detective_clues": [
            "Long crystals with stripes along the length",
            "Triangular cross-section",
            "Very hard — scratches steel",
            "Usually black (schorl) in Ontario",
        ],
        "dig_site_associations": ["bancroft", "haliburton"],
        "province_associations": ["Grenville"],
        "card_emoji": "🖊️",
        "card_colour": "#1c1917",
    },
    {
        "mineral_id": "garnet",
        "name": "Garnet",
        "family": "Silicate (Nesosilicate)",
        "rarity": "uncommon",
        "mohs_hardness": 7.0,
        "key_property": "Red 12-sided crystals, no cleavage",
        "ontario_locality": "Metamorphic rocks across Grenville Province",
        "flavour_text": "Ontario's favourite gem — found in the backyard!",
        "fun_fact": "Garnets are used in sandpaper and water jet cutters because they're so hard.",
        "age_easy_description": "A dark red crystal with 12 sides — like a bumpy ball.",
        "age_standard_description": "Nesosilicate group (almandine in Ontario); dodecahedral crystals; no cleavage.",
        "detective_clues": [
            "Dark red or reddish-brown colour",
            "Rounded bumpy shape with many faces",
            "Very hard — no cleavage, breaks unevenly",
            "Found in schist and gneiss",
        ],
        "dig_site_associations": ["bancroft", "haliburton"],
        "province_associations": ["Grenville"],
        "card_emoji": "🔴",
        "card_colour": "#7f1d1d",
    },
    {
        "mineral_id": "fluorite",
        "name": "Fluorite",
        "family": "Halide",
        "rarity": "uncommon",
        "mohs_hardness": 4.0,
        "key_property": "Perfect cubic cleavage, often purple or green",
        "ontario_locality": "Madoc area fluorite deposits",
        "flavour_text": "The most colourful mineral! Purple, green, blue, yellow...",
        "fun_fact": "Fluorescent light tubes get their name from fluorite — it glows under UV!",
        "age_easy_description": "A purple, green, or blue mineral that breaks into perfect little cubes.",
        "age_standard_description": "Calcium fluoride; perfect octahedral cleavage; often fluorescent under UV.",
        "detective_clues": [
            "Often purple, green, or blue",
            "Breaks into perfect shapes",
            "Softer than a pocket knife",
            "May glow under UV light",
        ],
        "dig_site_associations": ["madoc"],
        "province_associations": ["Grenville"],
        "card_emoji": "🟣",
        "card_colour": "#4c1d95",
    },
    {
        "mineral_id": "prehnite",
        "name": "Prehnite",
        "family": "Silicate",
        "rarity": "uncommon",
        "mohs_hardness": 6.5,
        "key_property": "Pale green botryoidal (grape-bunch) habit",
        "ontario_locality": "Lake Superior shoreline basalt cavities",
        "flavour_text": "It looks like a bunch of frozen green grapes!",
        "fun_fact": "Prehnite was the first mineral named after a person — Colonel Prehn of the Dutch army.",
        "age_easy_description": "A pale green mineral that grows in little rounded bumps like grapes.",
        "age_standard_description": "Calcium aluminum silicate hydroxide; pale green botryoidal aggregates.",
        "detective_clues": [
            "Pale green, almost mint colour",
            "Bumpy rounded surface like bubbles",
            "Often found with zeolite minerals",
            "Found in volcanic rock cavities",
        ],
        "dig_site_associations": [],
        "province_associations": ["Superior"],
        "card_emoji": "🍇",
        "card_colour": "#4d7c0f",
    },
    {
        "mineral_id": "stilbite",
        "name": "Stilbite",
        "family": "Silicate (Zeolite)",
        "rarity": "uncommon",
        "mohs_hardness": 3.5,
        "key_property": "Peach or white sheaf-like crystal clusters",
        "ontario_locality": "Basalt amygdales near Lake Superior",
        "flavour_text": "It looks like a tiny bow-tie or wheat sheaf!",
        "fun_fact": "Stilbite is a zeolite — it can act like a sponge and absorb water.",
        "age_easy_description": "A peach or white mineral that grows in a fan or bow-tie shape.",
        "age_standard_description": "Zeolite group; monoclinic; bow-tie or sheaf-like crystal habit.",
        "detective_clues": [
            "Peach, orange-pink, or white colour",
            "Bow-tie or fan-shaped clusters",
            "Found inside volcanic rock holes",
            "Soft and easy to scratch",
        ],
        "dig_site_associations": [],
        "province_associations": ["Superior"],
        "card_emoji": "🎀",
        "card_colour": "#fbcfe8",
    },
    {
        "mineral_id": "rhodonite",
        "name": "Rhodonite",
        "family": "Silicate (Pyroxenoid)",
        "rarity": "uncommon",
        "mohs_hardness": 6.0,
        "key_property": "Pink with black manganese oxide veins",
        "ontario_locality": "Haliburton Highlands, Grenville Province",
        "flavour_text": "Pink with black spiderwebs — striking!",
        "fun_fact": "Rhodonite is named from the Greek word for rose.",
        "age_easy_description": "A pink mineral with black veins running through it, like a spider's web.",
        "age_standard_description": "Manganese inosilicate; pink with characteristic black MnO₂ veins.",
        "detective_clues": [
            "Pink or rose-red colour",
            "Black veins or patches throughout",
            "Harder than a copper coin",
            "Often massive (not individual crystals)",
        ],
        "dig_site_associations": ["haliburton"],
        "province_associations": ["Grenville"],
        "card_emoji": "🌸",
        "card_colour": "#9d174d",
    },
    {
        "mineral_id": "titanite",
        "name": "Titanite",
        "family": "Silicate (Nesosilicate)",
        "rarity": "uncommon",
        "mohs_hardness": 5.5,
        "key_property": "Wedge-shaped crystals, adamantine lustre",
        "ontario_locality": "Grenville pegmatites and skarns, Bancroft area",
        "flavour_text": "Also called sphene — it sparkles like a diamond!",
        "fun_fact": "Titanite has a higher fire (light dispersion) than diamond.",
        "age_easy_description": "A wedge-shaped crystal that sparkles with many colours like a tiny diamond.",
        "age_standard_description": "Calcium titanium silicate; monoclinic wedge crystals; very high refractive index.",
        "detective_clues": [
            "Wedge or envelope crystal shape",
            "Very sparkly — fire like a diamond",
            "Yellow, brown, or green colour",
            "Found in Bancroft pegmatites",
        ],
        "dig_site_associations": ["bancroft"],
        "province_associations": ["Grenville"],
        "card_emoji": "💫",
        "card_colour": "#78350f",
    },
    {
        "mineral_id": "zircon",
        "name": "Zircon",
        "family": "Silicate (Nesosilicate)",
        "rarity": "uncommon",
        "mohs_hardness": 7.5,
        "key_property": "Tiny tetragonal crystals, very heavy",
        "ontario_locality": "Grenville pegmatites and gneisses",
        "flavour_text": "Earth's oldest mineral — some are 4 billion years old!",
        "fun_fact": "Zircon crystals from Australia are 4.4 billion years old — the oldest material on Earth.",
        "age_easy_description": "A tiny heavy crystal — the oldest mineral on Earth!",
        "age_standard_description": "Zirconium silicate; tetragonal prisms and pyramids; very high specific gravity.",
        "detective_clues": [
            "Very small tetragonal crystals",
            "Surprisingly heavy for its size",
            "Brown, yellow, or colourless",
            "Very hard — scratches steel",
        ],
        "dig_site_associations": ["bancroft"],
        "province_associations": ["Grenville"],
        "card_emoji": "⏳",
        "card_colour": "#713f12",
    },
    {
        "mineral_id": "lepidolite",
        "name": "Lepidolite",
        "family": "Silicate (Mica)",
        "rarity": "uncommon",
        "mohs_hardness": 2.8,
        "key_property": "Purple mica with lithium, pearlescent",
        "ontario_locality": "Tanco Mine area and Grenville pegmatites",
        "flavour_text": "The purple mica — and a source of lithium for batteries!",
        "fun_fact": "Lepidolite contains lithium — the same stuff in your phone battery.",
        "age_easy_description": "A purple sparkly mineral that peels into thin sheets like mica.",
        "age_standard_description": "Potassium lithium aluminum phyllosilicate; purple/lilac; lithium-bearing mica.",
        "detective_clues": [
            "Purple or lilac colour",
            "Peels into thin sparkly sheets",
            "Very soft",
            "Found in lithium-rich pegmatites",
        ],
        "dig_site_associations": [],
        "province_associations": ["Grenville"],
        "card_emoji": "💜",
        "card_colour": "#6b21a8",
    },
    {
        "mineral_id": "phlogopite",
        "name": "Phlogopite",
        "family": "Silicate (Mica)",
        "rarity": "uncommon",
        "mohs_hardness": 2.5,
        "key_property": "Golden-brown mica, star asterism sometimes",
        "ontario_locality": "Bancroft area — historically mined as industrial mica",
        "flavour_text": "Bancroft's golden mica — once used in spark plugs!",
        "fun_fact": "Phlogopite mica was mined near Bancroft for electrical insulation in cars.",
        "age_easy_description": "A golden-brown shiny mineral that peels into sheets like muscovite.",
        "age_standard_description": "Magnesium potassium phyllosilicate; bronze to golden-brown; from marble and carbonatite.",
        "detective_clues": [
            "Golden to dark brown colour",
            "Peels into thin shiny sheets",
            "Found in marble or carbonatite",
            "Bancroft is the classic Ontario locality",
        ],
        "dig_site_associations": ["bancroft"],
        "province_associations": ["Grenville"],
        "card_emoji": "🏅",
        "card_colour": "#92400e",
    },
    {
        "mineral_id": "celestite",
        "name": "Celestite",
        "family": "Sulfate",
        "rarity": "uncommon",
        "mohs_hardness": 3.5,
        "key_property": "Pale blue tabular crystals, heavy",
        "ontario_locality": "Southwestern Ontario evaporite formations",
        "flavour_text": "Sky-blue crystals named after the heavens!",
        "fun_fact": "Celestite is the primary source of strontium, used in fireworks for red colour.",
        "age_easy_description": "A pale blue mineral that looks like frozen sky.",
        "age_standard_description": "Strontium sulfate; orthorhombic; pale blue tabular crystals; high specific gravity.",
        "detective_clues": [
            "Pale blue or sky blue colour",
            "Tabular (flat) crystals",
            "Heavier than expected",
            "Found in southern Ontario limestone",
        ],
        "dig_site_associations": [],
        "province_associations": ["Southern and Superior"],
        "card_emoji": "🩵",
        "card_colour": "#0284c7",
    },
    {
        "mineral_id": "gypsum",
        "name": "Gypsum",
        "family": "Sulfate",
        "rarity": "uncommon",
        "mohs_hardness": 2.0,
        "key_property": "Softest common mineral, fingernail scratches it",
        "ontario_locality": "Southwestern Ontario evaporite beds",
        "flavour_text": "Blackboard chalk and plaster are made from gypsum!",
        "fun_fact": "Selenite is a clear variety of gypsum — you can see through it like glass.",
        "age_easy_description": "A very soft white mineral — so soft your fingernail can scratch it.",
        "age_standard_description": "Calcium sulfate dihydrate; Mohs 2 reference; selenite, satin spar, alabaster varieties.",
        "detective_clues": [
            "Fingernail easily scratches it",
            "White, clear, or pink colour",
            "Feels smooth",
            "From evaporite deposits in southern Ontario",
        ],
        "dig_site_associations": [],
        "province_associations": ["Southern and Superior"],
        "card_emoji": "🤍",
        "card_colour": "#f1f5f9",
    },
    # ── RARE ──────────────────────────────────────────────────────────────────
    {
        "mineral_id": "amethyst",
        "name": "Amethyst",
        "family": "Silicate (Quartz variety)",
        "rarity": "rare",
        "mohs_hardness": 7.0,
        "key_property": "Purple quartz, colour from iron impurities",
        "ontario_locality": "Thunder Bay — world's finest amethyst deposits",
        "flavour_text": "Thunder Bay is the amethyst capital of Canada!",
        "fun_fact": "Amethyst was once as valuable as ruby — until huge deposits were found in Brazil.",
        "age_easy_description": "A beautiful purple crystal — Thunder Bay is famous for these!",
        "age_standard_description": "Silicon dioxide with iron impurities producing violet colour; Thunder Bay deposits.",
        "detective_clues": [
            "Purple or violet colour",
            "6-sided crystal points",
            "Same hardness as clear quartz",
            "Thunder Bay, Ontario is the best place to find it",
        ],
        "dig_site_associations": ["thunder-bay"],
        "province_associations": ["Superior"],
        "card_emoji": "💜",
        "card_colour": "#5b21b6",
    },
    {
        "mineral_id": "sodalite",
        "name": "Sodalite",
        "family": "Silicate (Feldspathoid)",
        "rarity": "rare",
        "mohs_hardness": 6.0,
        "key_property": "Royal blue with white calcite veins",
        "ontario_locality": "Bancroft area — the only commercial deposit in the world!",
        "flavour_text": "Bancroft has the only sodalite mine in the world!",
        "fun_fact": "The blue sodalite at Bancroft is found nowhere else in commercial quantities on Earth.",
        "age_easy_description": "A deep blue mineral with white streaks — only found in Bancroft, Ontario!",
        "age_standard_description": "Sodium aluminum silicate chloride feldspathoid; brilliant royal blue; Bancroft unique.",
        "detective_clues": [
            "Bright royal blue colour",
            "White calcite veins throughout",
            "No crystal faces — massive habit",
            "Only Bancroft has a mine",
        ],
        "dig_site_associations": ["bancroft"],
        "province_associations": ["Grenville"],
        "card_emoji": "🔵",
        "card_colour": "#1d4ed8",
    },
    {
        "mineral_id": "amazonite",
        "name": "Amazonite",
        "family": "Silicate (Feldspar variety)",
        "rarity": "rare",
        "mohs_hardness": 6.0,
        "key_property": "Vivid blue-green microcline feldspar",
        "ontario_locality": "Grenville pegmatites, Bancroft and Haliburton",
        "flavour_text": "The green feldspar named after the Amazon River!",
        "fun_fact": "Despite the name, the best amazonite in North America comes from Ontario and Colorado.",
        "age_easy_description": "A bright green crystal that looks like sea glass.",
        "age_standard_description": "Lead-bearing microcline feldspar; intense blue-green from lead and water impurities.",
        "detective_clues": [
            "Bright blue-green colour",
            "Blocky crystal shape like other feldspars",
            "Two cleavage planes at right angles",
            "Found in Bancroft pegmatites",
        ],
        "dig_site_associations": ["bancroft", "haliburton"],
        "province_associations": ["Grenville"],
        "card_emoji": "💚",
        "card_colour": "#065f46",
    },
    {
        "mineral_id": "corundum",
        "name": "Corundum",
        "family": "Oxide",
        "rarity": "rare",
        "mohs_hardness": 9.0,
        "key_property": "Barrel-shaped hexagonal crystals, extremely hard",
        "ontario_locality": "Craigmont Mine, Renfrew County — sapphire-quality",
        "flavour_text": "Ruby and sapphire are both corundum — just different colours!",
        "fun_fact": "Corundum is so hard it's used to polish other gemstones.",
        "age_easy_description": "A very hard barrel-shaped crystal — rubies and sapphires are made of this!",
        "age_standard_description": "Aluminum oxide; rhombohedral crystals; Mohs 9 reference; ruby=red, sapphire=blue.",
        "detective_clues": [
            "Barrel or spindle shaped crystals",
            "Extremely hard — scratches everything",
            "Grey or blue-grey in Ontario",
            "Found near Renfrew County",
        ],
        "dig_site_associations": [],
        "province_associations": ["Grenville"],
        "card_emoji": "🔷",
        "card_colour": "#1e3a5f",
    },
    {
        "mineral_id": "beryl",
        "name": "Beryl",
        "family": "Silicate (Cyclosilicate)",
        "rarity": "rare",
        "mohs_hardness": 7.5,
        "key_property": "Hexagonal columns, many gem varieties",
        "ontario_locality": "Grenville pegmatites, Bancroft and Haliburton areas",
        "flavour_text": "Emerald, aquamarine, and morganite are all beryl!",
        "fun_fact": "Beryl can grow crystals up to 6 metres long in pegmatites.",
        "age_easy_description": "A six-sided column crystal — emeralds and aquamarines are types of beryl!",
        "age_standard_description": "Beryllium aluminum cyclosilicate; hexagonal prisms; many gem varieties by colour.",
        "detective_clues": [
            "Long 6-sided column shape",
            "Green, yellow, or white in Ontario",
            "Very hard — scratches steel",
            "No obvious cleavage",
        ],
        "dig_site_associations": ["bancroft", "haliburton"],
        "province_associations": ["Grenville"],
        "card_emoji": "💎",
        "card_colour": "#064e3b",
    },
    {
        "mineral_id": "hackmanite",
        "name": "Hackmanite",
        "family": "Silicate (Feldspathoid)",
        "rarity": "rare",
        "mohs_hardness": 5.8,
        "key_property": "Tenebrescent: fades in sunlight, glows orange under UV",
        "ontario_locality": "Bancroft — world's best tenebrescent hackmanite",
        "flavour_text": "It changes colour! UV makes it glow, sunlight makes it fade.",
        "fun_fact": "Hackmanite is tenebrescent — it turns pink in the dark and fades white in sunlight.",
        "age_easy_description": "A magical mineral that glows bright orange under a UV light!",
        "age_standard_description": "Sulfur-bearing sodalite; tenebrescent — reversibly changes colour with UV exposure.",
        "detective_clues": [
            "Pink when fresh, fades white in sun",
            "Bright orange glow under UV light",
            "Looks like sodalite but with sulphur smell",
            "Only Bancroft has top-quality specimens",
        ],
        "dig_site_associations": ["bancroft"],
        "province_associations": ["Grenville"],
        "card_emoji": "🌟",
        "card_colour": "#7c3aed",
    },
    {
        "mineral_id": "spessartine",
        "name": "Spessartine Garnet",
        "family": "Silicate (Nesosilicate)",
        "rarity": "rare",
        "mohs_hardness": 7.5,
        "key_property": "Orange to orange-red dodecahedral crystals",
        "ontario_locality": "Grenville pegmatites, rare but spectacular",
        "flavour_text": "Orange garnets — rarer and more valuable than red!",
        "fun_fact": "The finest spessartine comes from Nigeria, but Ontario has excellent specimens.",
        "age_easy_description": "A bright orange or reddish-orange bumpy crystal — rarer than red garnet.",
        "age_standard_description": "Manganese aluminum nesosilicate; orange to red-orange; dodecahedral habit.",
        "detective_clues": [
            "Orange or orange-red colour",
            "Rounded bumpy shape like all garnets",
            "No cleavage — breaks unevenly",
            "Rare in Ontario — a special find",
        ],
        "dig_site_associations": [],
        "province_associations": ["Grenville"],
        "card_emoji": "🟠",
        "card_colour": "#c2410c",
    },
    {
        "mineral_id": "eudialyte",
        "name": "Eudialyte",
        "family": "Silicate (Cyclosilicate)",
        "rarity": "rare",
        "mohs_hardness": 5.0,
        "key_property": "Pink-red in nepheline syenite, complex chemistry",
        "ontario_locality": "Kipawa Complex, Québec border / rare in Grenville",
        "flavour_text": "One of the rarest minerals in Ontario!",
        "fun_fact": "Eudialyte contains rare earth elements — critical for electric motors.",
        "age_easy_description": "A pink-red mineral found only in very special alkaline rocks.",
        "age_standard_description": "Complex Na-Ca-Fe-Zr cyclosilicate; pink to red; in nepheline syenite complexes.",
        "detective_clues": [
            "Pink to red colour",
            "Found in dark grey nepheline syenite rock",
            "No single perfect crystals",
            "Very rare — a major find",
        ],
        "dig_site_associations": [],
        "province_associations": ["Grenville"],
        "card_emoji": "🩷",
        "card_colour": "#be185d",
    },
    {
        "mineral_id": "columbite",
        "name": "Columbite-Tantalite",
        "family": "Oxide",
        "rarity": "rare",
        "mohs_hardness": 6.0,
        "key_property": "Black, submetallic, very heavy",
        "ontario_locality": "Tanco Mine and Grenville pegmatites",
        "flavour_text": "The ore of niobium and tantalum — used in phones and jets!",
        "fun_fact": "Tantalum from columbite is in every smartphone — it helps store electrical charge.",
        "age_easy_description": "A heavy black mineral found in rare pegmatites — used in smartphones!",
        "age_standard_description": "Iron-manganese niobium-tantalum oxide series; submetallic; very high density.",
        "detective_clues": [
            "Black, submetallic lustre",
            "Very heavy for its size",
            "Tabular or prismatic crystals",
            "From lithium-rich pegmatites",
        ],
        "dig_site_associations": [],
        "province_associations": ["Grenville"],
        "card_emoji": "📱",
        "card_colour": "#18181b",
    },
    {
        "mineral_id": "chrysoberyl",
        "name": "Chrysoberyl",
        "family": "Oxide",
        "rarity": "rare",
        "mohs_hardness": 8.5,
        "key_property": "Tabular crystals, extreme hardness, golden green",
        "ontario_locality": "Rare in Grenville pegmatites",
        "flavour_text": "Cat's-eye and alexandrite are chrysoberyl — one of the hardest gems!",
        "fun_fact": "Alexandrite chrysoberyl looks green in daylight and red under incandescent light.",
        "age_easy_description": "A very hard golden-green mineral — some change colour like magic!",
        "age_standard_description": "Beryllium aluminum oxide; tabular twinned crystals; Mohs 8.5; alexandrite variety.",
        "detective_clues": [
            "Golden yellow or greenish",
            "Very hard — scratches almost everything",
            "Tabular or twinned crystals",
            "Very rare in Ontario",
        ],
        "dig_site_associations": [],
        "province_associations": ["Grenville"],
        "card_emoji": "👁️",
        "card_colour": "#854d0e",
    },
    # ── LEGENDARY ─────────────────────────────────────────────────────────────
    {
        "mineral_id": "native-silver",
        "name": "Native Silver",
        "family": "Element",
        "rarity": "legendary",
        "mohs_hardness": 2.5,
        "key_property": "Wire or dendritic pure silver, very heavy",
        "ontario_locality": "Cobalt, Ontario — world-famous silver mining camp",
        "flavour_text": "Real silver! Cobalt had the richest silver veins on Earth.",
        "fun_fact": "The Cobalt silver camp produced over 450 million ounces of silver in the 1900s.",
        "age_easy_description": "Real silver growing in wire shapes — found in Cobalt, Ontario!",
        "age_standard_description": "Pure silver (Ag); wire, dendritic, or massive habit; Cobalt camp world-class.",
        "detective_clues": [
            "Pure white-silver metallic colour",
            "Very soft — fingernail nearly scratches it",
            "Grows in wire or branching shapes",
            "Found with red/orange arsenic minerals at Cobalt",
        ],
        "dig_site_associations": [],
        "province_associations": ["Superior"],
        "card_emoji": "🥈",
        "card_colour": "#94a3b8",
    },
    {
        "mineral_id": "native-copper",
        "name": "Native Copper",
        "family": "Element",
        "rarity": "legendary",
        "mohs_hardness": 3.0,
        "key_property": "Pure copper colour, massive or dendritic",
        "ontario_locality": "Lake Superior north shore and Keweenaw connection",
        "flavour_text": "Real copper — Indigenous peoples used this for thousands of years!",
        "fun_fact": "Lake Superior copper was traded across North America by Indigenous peoples 5,000 years ago.",
        "age_easy_description": "Real copper growing in rocks — people used it before metal was invented!",
        "age_standard_description": "Pure copper (Cu); copper-red when fresh, green patina; massive or dendritic habit.",
        "detective_clues": [
            "Unmistakable copper-red colour",
            "Green patina on the outside",
            "Heavy and malleable — bends",
            "Found along Lake Superior shoreline",
        ],
        "dig_site_associations": [],
        "province_associations": ["Superior"],
        "card_emoji": "🟤",
        "card_colour": "#92400e",
    },
    {
        "mineral_id": "gem-apatite",
        "name": "Gem Apatite",
        "family": "Phosphate",
        "rarity": "legendary",
        "mohs_hardness": 5.0,
        "key_property": "Gemstone-quality blue or green crystals, Bancroft",
        "ontario_locality": "Wilberforce and Bancroft — Ontario's finest gem minerals",
        "flavour_text": "Gemstone quality — these could be faceted into jewels!",
        "fun_fact": "Wilberforce apatite is considered some of the finest gem apatite on Earth.",
        "age_easy_description": "A beautiful blue or green crystal good enough to put in a ring!",
        "age_standard_description": "Gem-quality calcium phosphate; Wilberforce/Bancroft; blue to blue-green; facetable.",
        "detective_clues": [
            "Electric blue or sea-green colour",
            "Perfect hexagonal crystals",
            "Transparent or translucent",
            "Only the finest Wilberforce specimens qualify",
        ],
        "dig_site_associations": ["bancroft", "wilberforce"],
        "province_associations": ["Grenville"],
        "card_emoji": "💠",
        "card_colour": "#0369a1",
    },
    {
        "mineral_id": "hyalite-opal",
        "name": "Hyalite Opal",
        "family": "Silicate (Mineraloid)",
        "rarity": "legendary",
        "mohs_hardness": 6.0,
        "key_property": "Glass-clear gel opal, glows vivid green under UV",
        "ontario_locality": "Grenville pegmatites — rare coating on feldspar",
        "flavour_text": "Clear as glass — but glows neon green under UV light!",
        "fun_fact": "Hyalite glows neon green because of trace uranium in its structure.",
        "age_easy_description": "A see-through mineral that glows bright green under a UV light — rare!",
        "age_standard_description": "Amorphous hydrated silica; colourless gel; strong green UV fluorescence from uranium.",
        "detective_clues": [
            "Looks like clear jelly coating a crystal",
            "Glows vivid neon green under UV",
            "No crystal form — amorphous",
            "Extremely rare — a major find",
        ],
        "dig_site_associations": [],
        "province_associations": ["Grenville"],
        "card_emoji": "💚",
        "card_colour": "#14532d",
    },
    {
        "mineral_id": "polylithionite",
        "name": "Polylithionite",
        "family": "Silicate (Mica)",
        "rarity": "legendary",
        "mohs_hardness": 3.0,
        "key_property": "Iridescent lavender mica, extreme lithium content",
        "ontario_locality": "Tanco Mine, Manitoba / rare Grenville pegmatites",
        "flavour_text": "The rarest mica — iridescent lavender sheets!",
        "fun_fact": "Polylithionite has the highest lithium content of any mica mineral.",
        "age_easy_description": "A rare purple mica that shimmers with many colours — extremely rare!",
        "age_standard_description": "Lithium aluminum fluorine phyllosilicate; lavender; highest Li of any mica.",
        "detective_clues": [
            "Lavender to purple pearly sheets",
            "Strong iridescence on cleavage",
            "Found only in the richest pegmatites",
            "Extremely rare — legendary find",
        ],
        "dig_site_associations": [],
        "province_associations": ["Grenville"],
        "card_emoji": "🦄",
        "card_colour": "#5b21b6",
    },
]

BADGES = [
    # ── FIELD ──────────────────────────────────────────────────────────────────
    {
        "badge_id": "first-find",
        "name": "First Find",
        "category": "field",
        "description": "Logged your very first mineral find!",
        "icon": "🪨",
        "requirement": "Log 1 find in the Find Journal",
        "card_reward": "quartz",
    },
    {
        "badge_id": "hat-trick",
        "name": "Three-Find Hat Trick",
        "category": "field",
        "description": "Three mineral finds logged — you're a real rockhound!",
        "icon": "🎩",
        "requirement": "Log 3 finds in the Find Journal",
        "card_reward": "calcite",
    },
    {
        "badge_id": "province-pioneer",
        "name": "Province Pioneer",
        "category": "field",
        "description": "Found minerals in 2 different geological provinces.",
        "icon": "🗺️",
        "requirement": "Log finds from 2 different geological provinces",
        "card_reward": "feldspar",
    },
    {
        "badge_id": "full-shield",
        "name": "Full Shield",
        "category": "field",
        "description": "Found minerals in all four Ontario geological provinces!",
        "icon": "🛡️",
        "requirement": "Log finds from Grenville, Superior, Southern, and Churchill provinces",
        "card_reward": "garnet",
    },
    {
        "badge_id": "photo-geologist",
        "name": "Photo Geologist",
        "category": "field",
        "description": "Submitted a find with a photo — the scientists need pictures!",
        "icon": "📸",
        "requirement": "Log a find with at least one photo",
        "card_reward": "muscovite",
    },
    {
        "badge_id": "citizen-scientist",
        "name": "Citizen Scientist",
        "category": "field",
        "description": "Your find is eligible for the Ontario Geological Survey dataset!",
        "icon": "🔬",
        "requirement": "Submit a citizen science eligible find (GPS + photo + host rock + AI ID)",
        "card_reward": "apatite",
    },
    {
        "badge_id": "master-collector",
        "name": "Master Collector",
        "category": "field",
        "description": "Ten finds logged — you're a serious rockhound!",
        "icon": "🏆",
        "requirement": "Log 10 finds in the Find Journal",
        "card_reward": "tourmaline",
    },
    # ── KNOWLEDGE ─────────────────────────────────────────────────────────────
    {
        "badge_id": "rock-detective-rookie",
        "name": "Rock Detective Rookie",
        "category": "knowledge",
        "description": "Solved your first Rock Detective case!",
        "icon": "🔍",
        "requirement": "Solve 1 Rock Detective case",
        "card_reward": "pyrite",
    },
    {
        "badge_id": "rock-detective-case-closed",
        "name": "Case Closed",
        "category": "knowledge",
        "description": "Solved 5 Rock Detective cases — the mystery deepens!",
        "icon": "🕵️",
        "requirement": "Solve 5 Rock Detective cases",
        "card_reward": "fluorite",
    },
    {
        "badge_id": "rock-detective-master",
        "name": "Master Detective",
        "category": "knowledge",
        "description": "Solved all Rock Detective cases — elementary!",
        "icon": "🎖️",
        "requirement": "Solve all 20 Rock Detective cases",
        "card_reward": "amethyst",
    },
    {
        "badge_id": "province-explorer",
        "name": "Province Explorer",
        "category": "knowledge",
        "description": "Explored all four Ontario geological provinces in Formation Explorer.",
        "icon": "🌍",
        "requirement": "Unlock all four provinces in Formation Explorer",
        "card_reward": "epidote",
    },
    {
        "badge_id": "deep-digger",
        "name": "Deep Digger",
        "category": "knowledge",
        "description": "Found a specimen at a premium Dig Site Simulator site.",
        "icon": "⛏️",
        "requirement": "Find a specimen at a premium dig site",
        "card_reward": "sphalerite",
    },
    {
        "badge_id": "mineral-scholar",
        "name": "Mineral Scholar",
        "category": "knowledge",
        "description": "Completed all 5 Field Track geology lessons!",
        "icon": "📚",
        "requirement": "Complete all Field Track lessons at /learn",
        "card_reward": "rhodonite",
    },
    {
        "badge_id": "complete-collection",
        "name": "Complete Collection",
        "category": "knowledge",
        "description": "Collected every card in the Specimen Collector! Legendary!",
        "icon": "✨",
        "requirement": "Collect all 45 mineral cards",
        "card_reward": None,
    },
    # ── ENGAGEMENT ────────────────────────────────────────────────────────────
    {
        "badge_id": "site-visitor",
        "name": "Site Visitor",
        "category": "engagement",
        "description": "Booked a real Digby dig site — adventure awaits!",
        "icon": "🏕️",
        "requirement": "Complete a site booking",
        "card_reward": "chalcopyrite",
    },
    {
        "badge_id": "return-explorer",
        "name": "Return Explorer",
        "category": "engagement",
        "description": "Booked two different Digby sites — you love the outdoors!",
        "icon": "🔄",
        "requirement": "Complete bookings at 2 different sites",
        "card_reward": "galena",
    },
    {
        "badge_id": "gear-up",
        "name": "Gear Up",
        "category": "engagement",
        "description": "Made your first purchase from the Digby shop!",
        "icon": "🛒",
        "requirement": "Complete a shop order",
        "card_reward": "dolomite",
    },
    {
        "badge_id": "seven-day-streak",
        "name": "7-Day Streak",
        "category": "engagement",
        "description": "Logged in 7 days in a row — dedication!",
        "icon": "🔥",
        "requirement": "Log in 7 days in a row",
        "card_reward": "hematite",
    },
    {
        "badge_id": "season-regular",
        "name": "Season Regular",
        "category": "engagement",
        "description": "Active on Digby for a full season (3 months)!",
        "icon": "🌿",
        "requirement": "Active account for 90+ days",
        "card_reward": "prehnite",
    },
]

DETECTIVE_CASES = [
    {
        "case_id": "case-01",
        "title": "The Sparkly Thief",
        "region": "Bancroft, Ontario",
        "difficulty": "easy",
        "scene": (
            "A visitor to a Bancroft dig site found a sparkly silver mineral peeling "
            "apart in their hand into thin flat sheets. It was very shiny and very soft."
        ),
        "clues": [
            "It peeled into thin flat sheets",
            "The sheets were springy and flexible",
            "It was silvery and very shiny",
            "It was softer than a fingernail",
        ],
        "options": ["Quartz", "Muscovite Mica", "Calcite", "Pyrite"],
        "correct_id": "muscovite",
        "explanation": (
            "Muscovite mica peels into thin silvery sheets that are flexible and springy. "
            "It's very soft (Mohs 2.5) and found in Bancroft pegmatites."
        ),
        "unlock_day": 0,
        "card_reward_rare": "muscovite",
        "card_reward_uncommon": "feldspar",
        "card_reward_common": "quartz",
    },
    {
        "case_id": "case-02",
        "title": "The Fizzy Rock",
        "region": "Southern Ontario",
        "difficulty": "easy",
        "scene": (
            "A student poured a drop of vinegar on a white rock from a southern Ontario "
            "creek bed. The rock immediately started bubbling and fizzing!"
        ),
        "clues": [
            "It fizzed vigorously with vinegar",
            "It was white and chalky",
            "It scratched easily with a copper coin",
            "It broke into rhombus shapes",
        ],
        "options": ["Quartz", "Gypsum", "Calcite", "Feldspar"],
        "correct_id": "calcite",
        "explanation": (
            "Calcite (calcium carbonate) fizzes strongly with acid because it releases CO2 gas. "
            "It's soft (Mohs 3) and breaks into rhombus-shaped pieces."
        ),
        "unlock_day": 0,
        "card_reward_rare": "calcite",
        "card_reward_uncommon": "dolomite",
        "card_reward_common": "quartz",
    },
    {
        "case_id": "case-03",
        "title": "Fool's Gold Fever",
        "region": "Sudbury Basin",
        "difficulty": "easy",
        "scene": (
            "A young rockhound found a shiny yellow mineral near Sudbury and was convinced "
            "they'd struck it rich. But their geologist uncle shook his head and asked for the streak plate."
        ),
        "clues": [
            "Brassy yellow, very shiny",
            "Formed in cube shapes with striped faces",
            "Left a greenish-black powder on the streak plate",
            "Scratched glass easily",
        ],
        "options": ["Gold", "Pyrite", "Chalcopyrite", "Sphalerite"],
        "correct_id": "pyrite",
        "explanation": (
            "Pyrite (fool's gold) looks like gold but has a greenish-black streak and forms "
            "perfect cubes. Real gold is softer and has a gold streak."
        ),
        "unlock_day": 0,
        "card_reward_rare": "pyrite",
        "card_reward_uncommon": "chalcopyrite",
        "card_reward_common": "magnetite",
    },
    {
        "case_id": "case-04",
        "title": "Thunder Bay Purple",
        "region": "Thunder Bay, Ontario",
        "difficulty": "easy",
        "scene": (
            "A family visiting Thunder Bay found a cluster of deep purple crystals with "
            "6 sides inside a hollow rock. The crystals pointed upward like tiny towers."
        ),
        "clues": [
            "Deep purple colour",
            "6-sided pointed crystal tips",
            "Extremely hard — scratched glass easily",
            "Thunder Bay is famous for this mineral",
        ],
        "options": ["Fluorite", "Amethyst", "Sodalite", "Lepidolite"],
        "correct_id": "amethyst",
        "explanation": (
            "Amethyst is purple quartz found famously near Thunder Bay. Its 6-sided crystal "
            "points and extreme hardness (Mohs 7) distinguish it from purple fluorite and sodalite."
        ),
        "unlock_day": 3,
        "card_reward_rare": "amethyst",
        "card_reward_uncommon": "fluorite",
        "card_reward_common": "quartz",
    },
    {
        "case_id": "case-05",
        "title": "The Blue Bancroft Mystery",
        "region": "Bancroft, Ontario",
        "difficulty": "easy",
        "scene": (
            "A rockhound found a vivid royal blue massive mineral at a Bancroft quarry. "
            "It had white veins running through it and no individual crystals."
        ),
        "clues": [
            "Royal blue colour with white veins",
            "No individual crystal shape — massive",
            "Only Bancroft has a commercial mine for it",
            "Harder than calcite",
        ],
        "options": ["Fluorite", "Beryl", "Sodalite", "Azurite"],
        "correct_id": "sodalite",
        "explanation": (
            "Bancroft sodalite is the only commercial sodalite deposit in the world. "
            "Its royal blue colour with white calcite veins is unmistakable."
        ),
        "unlock_day": 3,
        "card_reward_rare": "sodalite",
        "card_reward_uncommon": "fluorite",
        "card_reward_common": "calcite",
    },
    {
        "case_id": "case-06",
        "title": "The Magnetic Mystery",
        "region": "Northern Ontario",
        "difficulty": "easy",
        "scene": (
            "A prospector was using a compass in northern Ontario when the needle kept "
            "spinning toward a black rock on the ground. The rock attracted their iron key."
        ),
        "clues": [
            "Strongly attracted to iron and a magnet",
            "Jet black colour",
            "Black streak",
            "Found in iron formations",
        ],
        "options": ["Hematite", "Galena", "Magnetite", "Hornblende"],
        "correct_id": "magnetite",
        "explanation": (
            "Magnetite (Fe₃O₄) is the only common strongly magnetic mineral. "
            "Hematite is not magnetic; galena is heavy but silvery; hornblende doesn't attract metal."
        ),
        "unlock_day": 6,
        "card_reward_rare": "magnetite",
        "card_reward_uncommon": "hematite",
        "card_reward_common": "hornblende",
    },
    {
        "case_id": "case-07",
        "title": "The Rainbow Ore",
        "region": "Sudbury, Ontario",
        "difficulty": "medium",
        "scene": (
            "At the Sudbury mining museum, a display case showed a yellow mineral "
            "with beautiful purple and blue iridescent tarnish on its surface. The sign said "
            "it was the main ore of an important metal used in wiring."
        ),
        "clues": [
            "Brassy yellow with purple/blue surface tarnish",
            "Softer than pyrite — copper coin scratches it",
            "Greenish-black streak",
            "Main copper ore mineral",
        ],
        "options": ["Pyrite", "Chalcopyrite", "Sphalerite", "Galena"],
        "correct_id": "chalcopyrite",
        "explanation": (
            "Chalcopyrite is the world's most important copper ore. Its rainbow iridescence "
            "on the surface and lower hardness than pyrite are key identifiers."
        ),
        "unlock_day": 6,
        "card_reward_rare": "chalcopyrite",
        "card_reward_uncommon": "pyrite",
        "card_reward_common": "hornblende",
    },
    {
        "case_id": "case-08",
        "title": "The Heavy Suspect",
        "region": "Cobalt, Ontario",
        "difficulty": "medium",
        "scene": (
            "An antique dealer found a small silver-grey cube in an old mineral collection "
            "labelled 'Cobalt mine, 1910.' It weighed surprisingly much and broke cleanly "
            "into cube shapes along three directions."
        ),
        "clues": [
            "Shiny silver-grey metallic colour",
            "Breaks into perfect cubes",
            "Extremely heavy for its size",
            "Grey streak",
        ],
        "options": ["Magnetite", "Galena", "Silver", "Pyrite"],
        "correct_id": "galena",
        "explanation": (
            "Galena (lead sulfide) is famous for its perfect cubic cleavage and extreme "
            "density. Cobalt mines produced galena as a byproduct of silver mining."
        ),
        "unlock_day": 9,
        "card_reward_rare": "galena",
        "card_reward_uncommon": "hematite",
        "card_reward_common": "magnetite",
    },
    {
        "case_id": "case-09",
        "title": "The Pistachio Puzzle",
        "region": "Lake Superior Shore",
        "difficulty": "medium",
        "scene": (
            "A hiker along the Lake Superior shoreline found a distinctive yellowish-green "
            "mineral growing in long crystals with lines running along their length. "
            "The crystals were harder than glass."
        ),
        "clues": [
            "Pistachio or olive green colour",
            "Long crystals with stripes along the length",
            "Harder than glass",
            "Found in altered volcanic rock",
        ],
        "options": ["Chlorite", "Tourmaline", "Epidote", "Beryl"],
        "correct_id": "epidote",
        "explanation": (
            "Epidote's distinctive pistachio-green colour and striated prismatic crystals "
            "are unique. Chlorite is softer and soapy; tourmaline is usually black in Ontario."
        ),
        "unlock_day": 9,
        "card_reward_rare": "epidote",
        "card_reward_uncommon": "chlorite",
        "card_reward_common": "hornblende",
    },
    {
        "case_id": "case-10",
        "title": "The Bubble Clusters",
        "region": "Lake Superior, Ontario",
        "difficulty": "medium",
        "scene": (
            "Inside a rounded cavity in a basalt boulder near Lake Superior, a collector "
            "found a mass of pale green rounded bumps that looked like frozen soap bubbles. "
            "The mineral felt slightly waxy."
        ),
        "clues": [
            "Pale green, almost mint colour",
            "Rounded bumps like a bunch of grapes",
            "Found inside a volcanic rock hole",
            "Slightly waxy feel",
        ],
        "options": ["Stilbite", "Prehnite", "Chlorite", "Fluorite"],
        "correct_id": "prehnite",
        "explanation": (
            "Prehnite characteristically grows as pale green botryoidal (grape-like) masses "
            "in cavities in basalt around Lake Superior. Stilbite is bow-tie shaped; "
            "chlorite is soapy and platy."
        ),
        "unlock_day": 12,
        "card_reward_rare": "prehnite",
        "card_reward_uncommon": "stilbite",
        "card_reward_common": "quartz",
    },
    {
        "case_id": "case-11",
        "title": "The Bow-Tie Visitor",
        "region": "Lake Superior Basalt",
        "difficulty": "medium",
        "scene": (
            "Inside a basalt geode, a rockhound found peach-coloured crystals arranged "
            "in perfect bow-tie or fan shapes. The crystals were soft and came apart easily."
        ),
        "clues": [
            "Peach or orange-pink colour",
            "Fan or bow-tie shaped crystal clusters",
            "Found inside a volcanic rock cavity",
            "Soft — scratched by a copper coin",
        ],
        "options": ["Apatite", "Stilbite", "Rhodonite", "Celestite"],
        "correct_id": "stilbite",
        "explanation": (
            "Stilbite is a zeolite mineral known for its distinctive sheaf or bow-tie "
            "crystal habit and peach to pink-orange colour. It fills cavities in Lake Superior basalt."
        ),
        "unlock_day": 12,
        "card_reward_rare": "stilbite",
        "card_reward_uncommon": "prehnite",
        "card_reward_common": "calcite",
    },
    {
        "case_id": "case-12",
        "title": "The Pink Web",
        "region": "Haliburton Highlands",
        "difficulty": "medium",
        "scene": (
            "In the Haliburton Highlands, a collector found a massive pink rock "
            "with striking black veins running through it like a spiderweb. "
            "It was harder than a pocket knife."
        ),
        "clues": [
            "Pink to rose-red colour",
            "Black veins or patches throughout",
            "Harder than a pocket knife (Mohs 6)",
            "Found in metamorphic rocks",
        ],
        "options": ["Fluorite", "Rhodonite", "Rose Quartz", "Lepidolite"],
        "correct_id": "rhodonite",
        "explanation": (
            "Rhodonite's diagnostic feature is its pink colour with black manganese oxide "
            "veins — unmistakable. Rose quartz has no black veins; fluorite is much softer."
        ),
        "unlock_day": 15,
        "card_reward_rare": "rhodonite",
        "card_reward_uncommon": "garnet",
        "card_reward_common": "feldspar",
    },
    {
        "case_id": "case-13",
        "title": "The Glowing Geode",
        "region": "Madoc, Ontario",
        "difficulty": "medium",
        "scene": (
            "At a Madoc mineral show, a vendor shone a UV light on a purple cubic "
            "mineral. It immediately glowed bright blue-white. The mineral broke into "
            "perfect shapes and was softer than a pocket knife."
        ),
        "clues": [
            "Purple or green colour in regular light",
            "Glows strongly under UV light",
            "Breaks into perfect shapes (octahedral cleavage)",
            "Softer than a pocket knife",
        ],
        "options": ["Sodalite", "Amethyst", "Fluorite", "Hackmanite"],
        "correct_id": "fluorite",
        "explanation": (
            "Fluorite is famous for UV fluorescence (the word 'fluorescent' comes from fluorite). "
            "Its perfect cleavage and Mohs 4 hardness distinguish it from amethyst and sodalite."
        ),
        "unlock_day": 15,
        "card_reward_rare": "fluorite",
        "card_reward_uncommon": "amethyst",
        "card_reward_common": "calcite",
    },
    {
        "case_id": "case-14",
        "title": "The Pencil Crystal",
        "region": "Bancroft Pegmatites",
        "difficulty": "medium",
        "scene": (
            "Digging in a Bancroft pegmatite, a junior geologist found long black crystals "
            "with visible lines running along their length. Each crystal had a triangular "
            "cross-section and was very hard."
        ),
        "clues": [
            "Long black crystals with stripes",
            "Triangular cross-section",
            "Very hard — scratches steel",
            "From a lithium-rich pegmatite",
        ],
        "options": ["Hornblende", "Tourmaline", "Biotite", "Columbite"],
        "correct_id": "tourmaline",
        "explanation": (
            "Black tourmaline (schorl) is identified by its striated prismatic crystals "
            "with triangular cross-sections. It's common in Ontario pegmatites. "
            "Hornblende doesn't form striated prisms."
        ),
        "unlock_day": 18,
        "card_reward_rare": "tourmaline",
        "card_reward_uncommon": "apatite",
        "card_reward_common": "feldspar",
    },
    {
        "case_id": "case-15",
        "title": "The Ancient Crystal",
        "region": "Grenville Province",
        "difficulty": "hard",
        "scene": (
            "A geologist showed a child a tiny but surprisingly heavy crystal under a "
            "magnifying glass. It had a perfect tetragonal shape and was found in a "
            "4-billion-year-old rock from the Grenville Province."
        ),
        "clues": [
            "Tiny tetragonal (4-sided) crystal",
            "Surprisingly heavy for its small size",
            "Brown or reddish colour",
            "Found in ancient Grenville gneiss",
        ],
        "options": ["Garnet", "Zircon", "Titanite", "Magnetite"],
        "correct_id": "zircon",
        "explanation": (
            "Zircon forms tetragonal crystals and has a very high specific gravity. "
            "It's found in Grenville gneisses and can be over 4 billion years old. "
            "It's much smaller and denser than garnet."
        ),
        "unlock_day": 21,
        "card_reward_rare": "zircon",
        "card_reward_uncommon": "titanite",
        "card_reward_common": "garnet",
    },
    {
        "case_id": "case-16",
        "title": "The Tenebrescent Trickster",
        "region": "Bancroft, Ontario",
        "difficulty": "hard",
        "scene": (
            "A mineral dealer showed two specimens — one was white, one was pink. "
            "She explained they were the same mineral. She put the white one under a "
            "UV light and it glowed vivid orange. Then she left the pink one in sunlight "
            "and it slowly turned white."
        ),
        "clues": [
            "Glows bright orange under UV light",
            "Turns pink in the dark, fades white in sunlight",
            "Related to sodalite",
            "Only Bancroft has top-quality specimens",
        ],
        "options": ["Sodalite", "Hackmanite", "Fluorite", "Willemite"],
        "correct_id": "hackmanite",
        "explanation": (
            "Hackmanite is tenebrescent sodalite — it reversibly changes colour with UV "
            "exposure. Fresh specimens are pink/violet and fade to white in sunlight. "
            "Under UV it glows vivid orange. Bancroft specimens are world-class."
        ),
        "unlock_day": 24,
        "card_reward_rare": "hackmanite",
        "card_reward_uncommon": "sodalite",
        "card_reward_common": "fluorite",
    },
    {
        "case_id": "case-17",
        "title": "The Phone Mineral",
        "region": "Grenville Pegmatites",
        "difficulty": "hard",
        "scene": (
            "A geologist told a group that a very heavy black mineral in a pegmatite "
            "contains an element used in every smartphone on Earth. The mineral had "
            "a submetallic lustre and tabular crystals."
        ),
        "clues": [
            "Black, submetallic lustre",
            "Very heavy for its size",
            "Tabular or prismatic crystals",
            "Contains tantalum — used in phones",
        ],
        "options": ["Magnetite", "Columbite-Tantalite", "Galena", "Uraninite"],
        "correct_id": "columbite",
        "explanation": (
            "Columbite-tantalite contains niobium and tantalum. Tantalum capacitors are "
            "in every smartphone. Its high density and submetallic lustre distinguish it "
            "from magnetite (which is magnetic) and galena (which is cubic)."
        ),
        "unlock_day": 27,
        "card_reward_rare": "columbite",
        "card_reward_uncommon": "zircon",
        "card_reward_common": "tourmaline",
    },
    {
        "case_id": "case-18",
        "title": "The Wire Silver",
        "region": "Cobalt, Ontario",
        "difficulty": "hard",
        "scene": (
            "In a museum display about Cobalt's famous silver rush, a specimen showed "
            "a bright white metallic mineral growing in thin wires and flat sheets. "
            "It was surprisingly soft for a metal."
        ),
        "clues": [
            "Pure white-silver metallic colour",
            "Grows in wires or flat branching shapes",
            "Very soft — almost scratched by a fingernail",
            "Found with red arsenic minerals at Cobalt",
        ],
        "options": ["Galena", "Platinum", "Native Silver", "Arsenopyrite"],
        "correct_id": "native-silver",
        "explanation": (
            "Native silver grows in wire, dendritic, or sheet habits. Cobalt was one of the "
            "world's richest silver camps. Its softness (Mohs 2.5) and wire habit are diagnostic. "
            "Galena is cubic and heavy; arsenopyrite is harder."
        ),
        "unlock_day": 30,
        "card_reward_rare": "native-silver",
        "card_reward_uncommon": "galena",
        "card_reward_common": "pyrite",
    },
    {
        "case_id": "case-19",
        "title": "The Diamond Wannabe",
        "region": "Bancroft, Ontario",
        "difficulty": "hard",
        "scene": (
            "A jeweller examined a small wedge-shaped crystal from Bancroft. "
            "Under a loupe, it sparkled with more fire than any diamond she'd seen. "
            "It was titanium-bearing and yellowish-brown."
        ),
        "clues": [
            "Wedge or envelope shaped crystal",
            "Fire (sparkle) exceeds diamond",
            "Yellow, brown, or green colour",
            "Contains titanium",
        ],
        "options": ["Zircon", "Titanite", "Chrysoberyl", "Beryl"],
        "correct_id": "titanite",
        "explanation": (
            "Titanite (sphene) has a higher refractive index than diamond, giving it "
            "exceptional fire. Its wedge-shaped crystals, titanium content, and Bancroft "
            "origin are all diagnostic clues."
        ),
        "unlock_day": 33,
        "card_reward_rare": "titanite",
        "card_reward_uncommon": "zircon",
        "card_reward_common": "apatite",
    },
    {
        "case_id": "case-20",
        "title": "The Neon Ghost",
        "region": "Grenville Province",
        "difficulty": "hard",
        "scene": (
            "Under normal light, a transparent gel-like coating on a feldspar crystal "
            "was almost invisible. But under a UV flashlight, it glowed vivid neon green. "
            "A geologist said it contained trace uranium."
        ),
        "clues": [
            "Nearly invisible in normal light",
            "Glows vivid neon green under UV",
            "Gel-like, no crystal form",
            "Contains trace uranium",
        ],
        "options": ["Willemite", "Hyalite Opal", "Fluorite", "Hackmanite"],
        "correct_id": "hyalite-opal",
        "explanation": (
            "Hyalite opal is amorphous silica that coats crystals and is virtually "
            "invisible in normal light. Trace uranium causes its brilliant neon green UV "
            "fluorescence. It's rare and legendary — a major find."
        ),
        "unlock_day": 36,
        "card_reward_rare": "hyalite-opal",
        "card_reward_uncommon": "hackmanite",
        "card_reward_common": "fluorite",
    },
]
